---
- hosts: "{{ hname }}"
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes

  tasks:

    - name: restart docker weekly At 00:00 on Sunday
      ansible.builtin.cron:
       name: "restart docker weekly"
       state: present
       minute: "0"
       hour: "0"
       day: "*"
       month: "*"
       weekday: "sun" # can be replaced sun with 0
       job: 'systemctl restart docker'
      tags: restartdocker 
    
    - name: restart redis At 00:20 every day
      ansible.builtin.cron:
       name: "restart redis every day"
       state: present
       minute: "20"
       hour: "0"
       day: "*"
       month: "*"
       weekday: "*"
       job: 'systemctl restart redis'
      tags: restartredis

    - name: Remove all unused containers, networks, images (both dangling and unreferenced), and optionally, volumes. At 00:10 every day
      ansible.builtin.cron:
       name: "docker system prune every day"
       state: present
       minute: "10"
       hour: "0"
       day: "*"
       month: "*"
       weekday: "*"
       job: 'docker system prune -f'
      tags: prune